// Assuming Navbar.js is your Navbar component
"use client";
import React from "react";

import { Inter } from "next/font/google";
import Navbar from "@/Component/Navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head></head>
      <body className={`h-screen ${inter.className}`}>
        <Navbar /> {/* Include the Navbar component here */}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
