// Assuming Navbar.js is your Navbar component

import React from "react";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
